### ISSUE TITLE
Getting auth() error

### ISSUE THREAD

**Issue by tarkanlar** [orchestrate-io/orcli#6]
Hi,
I am getting [Error: auth() received invalid user or password] although i write my api key properly

**Comment by garbados** [comment]
Can you enter the command you're running here? Without your API key, of course.

**Comment by tarkanlar** [comment]
orcli use $MY_API_KEY
i also tried 
orcli use $MY_API_KEY testing
then i type
orcli use testing
and again
 [Error: auth() received invalid user or password]

**Comment by garbados** [comment]
Hm. Email me at diana@orchestrate.io, yeah? I want to get enough data to reproduce the issue, but that data probably shouldn't go on a public thread D:

**Comment by garbados** [comment]
[Got it!](https://github.com/orchestrate-io/orcli/commit/4baa73b4762faee0e15d085ea466ed3ab8336433) Close out the issue if you find it resolved :)

**Comment by tarkanlar** [comment]
Thanks :+1:  Works perfect now
